### PR TITLE
Prevent loading of custom footer on content migrations page

### PR DESCRIPTION
**Pull request by PatrickMTonne**
Resolves[ TLT-4723](https://at-harvard.atlassian.net/browse/TLT-4723).

Example of updated theme without custom footer:

Screen Shot 2024-07-23 at 3 23 32 PM

### CODE REVIEW

**Comment by haydn9000** [comment]
It looks like `develop` is behind the `main` branch. Maybe pull from both branches to make sure you have all the latest changes (especially from the main branch since it has some of the updates related to similar changes), then we can do the usual (merge to develop then main) 🙂

**Comment by haydn9000** [comment]
Side note, at first glance it looks like this repo doesn't have a develop branch under the branches tab, which is why I think some of the branches created (that added some changes) were from main and merged to main directly skipping develop it seems 😅

**Comment by Chris-Thornton-Harvard** [comment]
We can delete the develop branch as this is a project not frequently worked on and keep main as the default branch to develop off of.  
I would start again based off of main

**Comment by PatrickMTonne** [comment]
Closing PR in favor of updated [PR](https://github.com/harvard-canvas-branding/catalog-branding-global/pull/14) based off `main`.

**Pull request closed without merging**
